platform :ios, '7.0'
inhibit_all_warnings!

pod 'AFNetworking'
pod 'ObjectiveSugar'
pod 'Antenna'
pod 'TTTAttributedLabel'

#pod 'SSToolkit'
#pod 'AFOAuth1Client', '~> 0.3.3'
pod 'oauthconsumer', :path => '~/Code/oauthconsumer/'
#pod 'UYLPasswordManager', :path => '~/Code/UYLPasswordManager'
#pod 'MWWindow', :path => '~/Code/MWWindow'
#pod 'IDMPhotoBrowser'
######## needs afnetworking 2 which restkit does not work with! pod 'IDMPhotoBrowser'
#pod 'KeychainItemWrapper', :path => '~/Code/KeychainItemWrapper'
pod 'FXKeychain'
pod 'MZFormSheetController'
#pod 'SSKeychain'
pod 'Bolts'
pod 'MRProgress', '~> 0.3.1'
pod 'TestFlightSDK', '~> 3.0.0'
pod 'ConciseKit'
pod 'SBJson', '~> 4.0.0'
pod 'MSWeakTimer', '~> 1.1.0'
pod 'Sequencer'
pod 'EZForm'
#pod 'MosaicUI', '~> 0.0.1'
#pod 'MosaicLayout', :path => '~/Code/MosaicLayout/MosaicCollectionView/Libs/MosaicLayout'
#pod 'UIView+AutoLayout'

#replace text fields in sign up with this?
#pod 'JVFloatLabeledTextField'
# uses lovely JVFloatLabeledTextField controls for the field labels!
#pod 'BPForms'

#pod 'NVDate'
pod 'US2FormValidator'

#pod 'HockeySDK-iOS', :git => 'https://github.com/bitstadium/HockeySDK-iOS.git', :branch => 'develop'

pod 'CRToast', :git => 'https://github.com/cruffenach/CRToast.git', :commit => '8187f23e1398f94b466c371f9cc1a3f9e1ffd234'
pod 'kvo-block-binding', :path => '~/Code/kvo-block-binding'
pod 'ViewUtils', '~> 1.1.2'
pod 'KeyboardController', '~> 1.0.0'
pod 'FLKAutoLayout'
pod 'MCUIViewLayout', :git => 'https://github.com/mirego/MCUIViewLayout.git'
pod 'WSLObjectSwitch', :path => '~/Code/WSLObjectSwitch'
pod 'RFRotate', :path => '~/Code/RFRotate'
pod 'AQGridView', '~> 1.3'
pod 'UIColor-Crayola'
#pod 'ionicons'
pod 'TYMActivityIndicatorView'
pod 'Masonry', '~> 0.4.0'

pod 'iCarousel', :git => 'https://github.com/bleeckerj/iCarousel'
#pod 'GMGridView'
pod 'RNCryptor', '~> 2.2'
pod 'MKFoundationKit', '~> 1.1.0'
pod 'FPBrandColors', '~> 0.1.3'
pod 'ionicons'
pod 'NSLogger'
pod 'MGBoxKit'
pod 'OCMock'
#pod 'BButton'
pod 'ReactiveCocoa'
#pod 'CoconutKit', '~> 2.0.2'
pod 'FlatUIKit'
pod 'TPKeyboardAvoiding'
pod 'RDVKeyboardAvoiding'
pod 'EKKeyboardAvoiding'
pod 'RNBlurModalView', '~> 0.1.0'
pod 'NHBalancedFlowLayout', '~> 0.1.2'
pod 'Facebook-iOS-SDK'
#pod 'ViewDeck' '~> 2.2.11'
#pod 'PKRevealController'
#pod 'ECSlidingViewController', '~> 2.0.0'
pod 'ECSlidingViewController', '~> 2.0.0-beta2'
pod 'MMDrawerController', '~> 0.5.2'
pod 'DropdownMenu'
pod 'REMenu', '~> 1.8'
pod 'FontAwesome-iOS', '~> 0.0.4'
#pod 'ECSlidingViewController', :path => '~/Code/ECSlidingViewController'
target :humansTests, :exclusive => true do
pod 'OCHamcrest', '~> 3.0.1'
  pod 'Expecta',     '~> 0.2.3'   # expecta matchers
    pod 'OCMockito', '~> 1.0'
end
####pod 'MGBoxKit'
pod 'MGBoxKit', :git => 'https://github.com/sobri909/MGBoxKit.git', :commit => '7474eef2cb16b7f1338607115b3dc0a92ef88e71'

pod 'UIImage-Categories', '~> 0.0.1'
#pod 'BlocksKit', :git => 'https://github.com/pandamonia/BlocksKit', :branch => 'next'
pod 'BlocksKit'
pod 'MBProgressHUD', '~> 0.8'
pod 'SDWebImage'
#pod 'UIDevice-Helpers', '~> 0.0.1'
#pod 'RFRotate'
pod 'MHTextField', '~> 0.0.3' #MHTextField is an iOS drop-in class that extends UITextField with built-in toolbar, validation and scrolling support.
pod 'SKSlideViewController', '~> 0.0.1' #SKSlideViewController is an easy to use, slide-to-navigate view controller for ios 6.0 +. It enables you to present a main view controller and an optional, direction-sensitive accessory view controller. It is easy to setup and modify.
# Testing and Search are optional components
#pod 'RestKit/Testing'
#pod 'RestKit/Search'


